name: boring_show_example
description: A new Flutter application.

dependencies:
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.5
  http: ^0.11.3
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^0.8.3
  built_value_generator: ^5.5.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

